### ISSUE TITLE
Get familiar with tool

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#2]
Use MySQL work bench and get out basic data. 

Using the **Sakila database** do the following.

Complete the following 
1. Get the list of stores
2.Get the list of films.

**Comment by aparnaraon** [comment]
> Use MySQL work bench and get out basic data.
> 
> Using the **Sakila database** do the following.
> 
> Complete the following
> 
> 1. Get the list of stores- SELECT * FROM sakila.store;
>    2.Get the list of films.-SELECT * FROM sakila.film;

1

**Comment by aparnaraon** [comment]
done
