### ISSUE TITLE
Do Join complex queries

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#3]
In the Sakila database get the list of flims in each store rented out by Staff id 2.

**Comment by aparnaraon** [comment]
will solve it after completing  exercise 1 & 2 assigned for Nov 2018 R1

**Comment by aparnaraon** [comment]
will  solve it after completion of exercise 1 & 2

**Comment by aparnaraon** [comment]
1.SELECT film.film_id, film.title, inventory.inventory_id, inventory.store_id, rental.staff_id, staff.first_name, staff.last_name
FROM film, inventory,rental, staff
WHERE film.film_id =inventory.film_id AND rental.inventory_id = inventory.inventory_id AND rental.staff_id = 2 
2, additonal conditions added- 
AND inventory.store_id= 1  AND rental.staff_id = staff.staff_id;

**Comment by aparnaraon** [comment]
SELECT rental.inventory_id,film.film_id,film.title,inventory.store_id
FROM rental,film,inventory
WHERE rental.inventory_id = inventory.inventory_id
AND inventory.film_id = film.film_id
AND rental.staff_id = 2 ;
