### ISSUE TITLE
UDEMY - Section 8

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#30]

**Comment by aparnaraon** [comment]
SECTION 8
LEARNINGS – 
1.	DISTINCT
2.	LIMIT
3.	ORDER BY
4.	LIKE

SOLUTIONS TO THE CHAPTER- REFINING SELECTIONS , Chapter 135
1.	SELECT title FROM books WHERE title LIKE '%stories%';
2.	Find the longest book-
•	select title, pages from books
•	order by pages DESC limit 1 ;
3.	Print a summary containing the title and year, for the 3 most recent books
•	SELECT  CONCAT_WS(‘ –  ‘ title , released_year)  AS Summary
•	FROM books
•	ORDER BY released_year DESC  LIMIT 3;
        		[OR]
•	select concat(title, ' - ', released_year) AS Summary  
•	from books
•	order by released_year desc limit 3 ;
4.	Find  ALL  books that has the author last name that has a space in it “ “
•	select title, author_lname
•	FROM books
•	WHERE author_lname like '% %';
5.	Find the 3 books with the lowest stock.  Select title, year and stock
•	select title, released_year, stock_quantity
•	FROM books
•	order by 3,2 DESC 
•	limit 3;
6.	PRINT title , author_lname,  sorted first by author_lname & then by title		
•	select title, author_lname FROM books
•	ORDER BY 2, 1;
7.	Sorted alphabetically by last name  AS yell
•	SELECT  CONCAT(“MY FAVOURITE AUTHOR IS”,
•	UPPER (author_fname),  ‘ ‘ ,
•	UPPER(author_lname),’!’ ) AS yell
•	FROM books
•	ORDER BY author_lname;
