### ISSUE TITLE
UDEMY - Section 9

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#31]

**Comment by aparnaraon** [comment]
3.	Print total no of books in the data base
•	SELECT COUNT(title)
•	FROM books;
       4. No of books released in each year
•	SELECT released_year, title
•	FROM books
•	GROUP BY released_year;
    5.Print out total no of books in stock
o	SELECT sum(stock_quantity)
o	FROM books;
5.	Find the average released year for each author
•	SELECT avg(released_year), author_lname, author_fname
•	FROM books
•	GROUP BY released_year;
6.	Find the FULLL NAME of the author who wrote the longest book
before CONCAT
o	SELECT max(pages) , title, author_lname, author_fname
o	FROM books 
o	group by 3,4
o	order by 1 desc LIMIT 1;
               after CONCAT
o	SELECT  concat( author_fname, ' ' , author_lname,' ', 'is the author who wrote', ' ', title, ' ', 'having', ' ', MAX(pages), ' ' , 'pages') AS LONGEST
o	FROM books 
o	group by author_fname, author_lname
o	order by pages desc LIMIT 1;
7.	Make this happen
•	SELECT released_year AS ‘year’
•	count(title) AS ‘books #’ , 
•	avg(pages) AS ‘avg pages’
•	FROM books
•	GROUP BY released_year
•	ORDER BY released_year;
