### ISSUE TITLE
Queries for Digest

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#37]
The following queries need to be done for the digest. 

1. Score board for all mentees 
2. Max checking-in per day 
3. Min checking / day
4. Max scorer of the week 
5. Max scoring team of the week
6. Person with maximum early check-in 
7. All the Challenge like CQA FOR The period.

**Comment by aparnaraon** [comment]
![RCG Fortnight May 31](https://user-images.githubusercontent.com/44048886/59319176-569d6380-8ce7-11e9-9eb5-f259fa0c970d.jpg)
completed
