### ISSUE TITLE
Calculating Full House for a Team

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#41]
A query is needed to determine if on a particular day if all the members of a team did checking-in. If they did it all the team members get an additional Team Full House points say 20 each. 

This should be a good motivation for each team member to get the other to check-in

The query can be done for one day. Then we can extend it for a week.

**Comment by aparnaraon** [comment]
[Team wise  check ins  afor the week ended  on 30 Jun 2019-CSS.xlsx](https://github.com/kumarana/Data-Analytics/files/3387030/Team.wise.check.ins.afor.the.week.ended.on.30.Jun.2019-CSS.xlsx)
completed
