### ISSUE TITLE
Understand the capabilities and Get from Thryve Teams.

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#44]
Look at the attached. And look at APQC site. https://www.apqc.org/

1. Look at the excel and understand Capabilities. 
2. Talk to all Thryve Teams and make a note of the Capbabilites for which they are make their project.

[Healthcare Provider_v721_vs_Healthcare Provider_v611.xlsx](https://github.com/kumarana/Data-Analytics/files/3802487/Healthcare.Provider_v721_vs_Healthcare.Provider_v611.xlsx)

**Comment by aparnaraon** [comment]
1. Talk to all Thryve Teams and make a note of the Capabilities for which they are make their project.- 
So the action that is taken by a mentee/ team has to be in sync with the capability listed already.
2. The relevant capability  which could be applicable has been marked in green
3. How do I tie up the capability with the intention identified by the mentee- intentions being- fast, economical, safe & easy
1

**Comment by kumarana** [comment]
![image](https://user-images.githubusercontent.com/6807325/68293688-7f6a2f00-00b4-11ea-96c8-9955ddef5ed6.png)

**Comment by kumarana** [comment]
Go through this article. 
https://docplayer.net/6198522-Business-capability-management-your-key-to-the-business-board-room-ulrich-kalex-alfabet-ag.html

**Comment by aparnaraon** [comment]
collected
