### ISSUE TITLE
Make a Value tracker For All team

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#45]
We need to track the value delivered in our programs. To this effect the following needs to be done

1. For every completed MVP the benefits need to tracked.,
2. The benefits can be Cost reduction (  hrs saved ) / Revenue increase / Cust Sat Inc / Emp Sat Inc 
2. Create the first version of this Value Tracker Spreadsheet for Thryve.

**Comment by aparnaraon** [comment]
Since the value tracking is for a _completed_ MVP, my starting point would be the CMJ , downloaded from Magiq Spark.
Draft enclosed- ver 1
[Thyrve value tracker.xlsx](https://github.com/kumarana/Data-Analytics/files/3813797/Thyrve.value.tracker.xlsx)
