### ISSUE TITLE
Magiq spark basic excercises

### ISSUE THREAD

**Issue by kumarana** [kumarana/Data-Analytics#7]
Please do these. 

1. Get a list of all groups in Magiqspark .
2. Get a list of all mentees in the following format GROUP NAME, MENTEE NAME, EMAIL , PHONE NUMBER
3. Get a list of all chains which are ACTIVE  for a group ( Use Chains table )
4. Get a list of users checked-in for Today for one chain for a group.  Use the above problem to identify the chain for  a group. 
4. Get a list of total checks a user has done till date for that chain.

**Comment by aparnaraon** [comment]
6. Rephrased  Q # 2 by replacing GROUP name with Whatsapp Group name.
Ans- SELECT app_users.name, app_users.email, app_users.phone, app_user_team.team_id, app_user_team.app_user_id,
groups.whatsapp_group
FROM app_users, magiqsparkkum.groups, app_user_team
WHERE app_users.id = app_user_id;

**Comment by aparnaraon** [comment]
1.	Get a list of all groups in Magiqspark .
•	SELECT *
•	from latestmagiqspark.groups;
•	no of rows returned = 79
2.	Get a list of all mentees in the following format GROUP NAME, MENTEE NAME, EMAIL , PHONE NUMBER
3.	Get a list of all chains which are ACTIVE  for a group ( Use Chains table )
(a)	For selecting a particular group- SPI, the group_id or code = 76
(i)	select * from latestmagiqspark.groups 
(ii)	WHERE organization = "SPI ";
(b)	To get list of chains active for the above group =014
(i)	select *  from Chains where group_id = 76 ;
(c)	To select / identify the chain- ILI tiny grit= 330  [chain _id]
4.	Get a list of users checked-in for Today for one chain for a group.  Use the above problem to identify the chain for  a group. Users checked in = 14 
select *
from latestmagiqspark.checks
INNER join chains
ON checks.chain_id = chains.id
WHERE chains.group_id  = 76 
and chain_id = 330
and checked_on = "2019-01-31";

5.	Get a list of total checks a user has done till date for that chain. 
(a)	I have randomly chosen  Harshil Mehta 
(b)	select *
from latestmagiqspark.checks
INNER join chains
ON checks.chain_id = chains.id
WHERE chains.group_id  = 76 
and chain_id = 330
and app_user _id = 
ADDITIONALLY DONE BY ME
6.	To get the Total no of app users -893 
•	SELECT name, email, phone
•	from latestmagiqspark.app_users;
7.	total no of active groups as on date-[ ie 7th Feb 2019] = 28 
•	select * from latestmagiqspark.groups 
•	WHERE  program_end_date >  "2019-02-07";
8.	And  organization = "
9.	Get a list of all mentees in the following format-whatsapp GROUP NAME, MENTEE NAME, EMAIL , PHONE NUMBER

10.	Get the no of Check ins for SPI Cinemas chain – Hi Po ha dossier submission.
•	SELECT *
•	from latestmagiqspark.checks
•	INNER join chains
•	ON checks.chain_id = chains.id
•	WHERE chains.group_id  = 76 
•	and chain_id = 327 ;


11.	No of active groups = 28
•	select * from latestmagiqspark.groups 
•	WHERE  program_end_date >  "2019-02-07"; 

12.	No of cognizant groups mentored which are active = 7
•	select * from latestmagiqspark.groups 
•	WHERE  program_end_date >  "2019-02-07"
•	And where organization = “cognizant “; 
13.	No of cognizant groups mentored so far = 10 [found them not active, ie.closed]
•	select * from latestmagiqspark.groups 
•	WHERE  program_end_date < "2019-02-07" and organization = "cognizant";
14.	Total no of cognizant groups mentored so far= 17
•	select * from latestmagiqspark.groups 
•	WHERE  organization = "cognizant";

15.	To select active groups and specifically SPI
•	select * from latestmagiqspark.groups 
•	WHERE organization = " SPI "  AND program_end_date >  "2019-02-07" ;
16.	Get the no of Check ins for SPI Cinemas chain –[ ILI chain_id = 330.] = 14
•	SELECT *
•	from latestmagiqspark.checks
•	INNER join chains
•	ON checks.chain_id = chains.id
•	WHERE chains.group_id  = 76 
•	and chain_id = 330 ;

**Comment by aparnaraon** [comment]
need to check on 2 things,

**Comment by aparnaraon** [comment]
1.

**Comment by aparnaraon** [comment]
Question No 2- Get the list of mentee,  names, ph no, email & their Groups
The query below is by using INNER JOIN
SELECT 
app_users.id,
app_users.name,
app_users.email,app_users.phone, 
latestmagiqspark.groups.name

FROM app_users

INNER JOIN 
app_user_group ON app_user_group.app_user_id = app_users.id  

INNER JOIN 
 latestmagiqspark.groups ON  latestmagiqspark.groups.id = app_user_group.group_id;
